### ISSUE TITLE
Invalid or unexpected token when transpiling PNG on next@9.5.2 with 4.1.0

### ISSUE THREAD

**Issue by GowsK93** [martpie/next-transpile-modules#113]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
Local Package

**Describe the bug**
Hello, 

I've currently got an app which is consuming a component library called `fe-components` and transpiling the module within my next config file.

`transpileModules: ['@itv/fe-cerberus', '@itv/fe-components', '@itv/fe-mortal', 'debug'],`

The issue that arrises is that it seems that file-loader configured in the config is not executing correctly or at all. It is treating a PNG import from `fe-components` as actual JS giving me an "Invalid or unexpected token" error like the one below:

```
2020-08-20T11:05:59.089Z - error: Invalid or unexpected token
/Users/sean/Dev/ITV/fe-core/packages/fe-components/lib/cjs/common/images/default-image.png:1
�PNG
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/sean/Dev/ITV/fe-core/packages/fe-components/lib/cjs/molecules/featured-tile/featured-tile.js:32:44)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

Here is the rule picking up PNG files for file-loader:

```
config.module.rules.push({
            test: /\.(png|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [
                {
                    loader: 'file-loader',
                    options: {
                        name: '[name].[contenthash].[ext]',
                        outputPath: 'static/'
                    }
                }
            ]
 });
```

The PNG in question has not been touched for some time but the issue has only cropped up since updating to the latest `next` version and corresponding recommended 'next-transpile-modules` version.

**Steps to replicate**
Tried best to provide a snapshot of what the next config looks like for the problem areas.

**Setup**
- Next.js version: 9.5.1
- `next-transpile-modules` version: 4.1.0
- Node.js version: 13.11.0
- `pnpm` version: 5.5.1
- Operating System: macOS
- Webpack 4 or 5: 4.43.0

Hopefully that explanation isn't too vague but feel free to ask for more info

**Comment by martpie** [comment]
Hello there, sorry for the late reply.

If you include this image directly in a folder in your Next.js app, does it work? In other words, are you sure it's a problem with `next-transpile-modules` and not your new Webpack rule?

**Comment by martpie** [comment]
Closing for inactivity, and new version of Next and `next-transpile-modules` are available and might fix this.
