### ISSUE TITLE
Trouble transpiling 'lodash-es' with Next.js 10.x

### ISSUE THREAD

**Issue by palerdot** [martpie/next-transpile-modules#144]
- [x ] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
`lodash-es` `npm` package

**Describe the bug**
`lodash-es` is throwing error. Sample next.js config 
```javascript
const withTM = require("next-transpile-modules")(["lodash-es"]);

module.exports = withTM();
```

**To Reproduce**
https://codesandbox.io/s/serene-worker-h094e?file=/pages/index.js

**Expected behavior**
`lodash-es` should work properly when used with `next-transpile modules`

**Setup**

- Next.js version: 10.x
- `next-transpile-modules` version: 6.x
- Node.js version: latest (codesandbox link attached)
- `npm`/`yarn` version: latest (codesandbox link attached)
- Operating System: any
- Webpack 4 or 5: not sure, whatever next.js 10 usees (codesandbox link attached)

**Additional context**
I maintain a package [react-d3-speedometer](https://github.com/palerdot/react-d3-speedometer), which uses `lodash-es` as a dependency. Since `lodash-es` has trouble working with `next.js`, I recommend this library to transpile stuffs. But, suddenly I find things are not working with next.js 10.x. I used the `debug: true` flag and saw that this library actually transpiles (or says it did transpile) the `node_modules/lodash-es` folder. But, things are not working still.

**Comment by martpie** [comment]
Hello 👋

Can you post the full log?

**Comment by martpie** [comment]
sidenote: the integration tests of this plugin use `lodash-es` as tests, so I am pretty confident it works fine ;)

**Comment by palerdot** [comment]
> Can you post the full log?
@martpie  I don't understand which log you are referring to. The one shown in console when using `debug: true`?

Also, I have shared a codesandbox where things are not working - https://codesandbox.io/s/serene-worker-h094e?file=/next.config.js:0-93

**Comment by martpie** [comment]
Yes, the whole console log, debug or not

**Comment by palerdot** [comment]
Here you go 
```
build page: /
wait  - compiling...
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isEmpty.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isArray.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/take.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/times.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/drop.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/last.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/head.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isArray.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isEmpty.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/sum.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isNumber.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseKeys.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isTypedArray.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_isPrototype.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isBuffer.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isArrayLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isArray.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isArguments.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseSlice.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/toInteger.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseSlice.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/toInteger.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseTimes.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/toInteger.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_castFunction.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseSum.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/identity.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObjectLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_isPrototype.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_nativeKeys.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseIsTypedArray.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isFunction.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseIsArguments.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_DataView.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_toSource.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_WeakMap.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_Set.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_Promise.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_Map.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObjectLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isLength.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/stubFalse.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_nodeUtil.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseUnary.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/toFinite.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/identity.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_Symbol.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_objectToString.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getRawTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_overArg.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isLength.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObjectLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObject.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_freeGlobal.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObjectLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_freeGlobal.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/toNumber.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_Symbol.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseIsNative.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_getValue.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObject.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isSymbol.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isFunction.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_isMasked.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObject.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_toSource.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_baseGetTag.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/isObjectLike.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_coreJsData.js
next-transpile-modules - transpiled: /my-package-path/node_modules/lodash-es/_root.js
event - compiled successfully
/my-package-path/node_modules/lodash-es/isNumber.js:1
import baseGetTag from './_baseGetTag.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1172:16)
    at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/my-package-path/node_modules/react-d3-speedometer/dist/core/util/index.js:1:616)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
/my-package-path/node_modules/lodash-es/isNumber.js:1
import baseGetTag from './_baseGetTag.js';
^^^^^^
```

**Comment by martpie** [comment]
mmh weird, [as you can see here](https://github.com/martpie/next-transpile-modules/blob/master/src/__tests__/__files__/pages/test-npm-module.jsx), `lodash-es` works well and test passes, maybe it's a `isNumber` thing 🤔

**Comment by palerdot** [comment]
Here is a vanilla sandbox with only `lodash-es` and `next-transpile-modules` - https://codesandbox.io/s/agitated-moore-6r1hx?file=/pages/index.js

> maybe it's a isNumber thing
That is the first `lodash-es` import in the library, so if `es6` is not supported, we will get the exact error, even in normal react apps where the build setup does not support `es6` modules (like very old build setups).

Any pointers to debug this would be appreciated. The way I see it, since this error is reproducible in any `next.js 10.x` with `lodash-es`, there might be more of this reports coming in. Also, do you see things working in your local with `next.js 10.x` and `lodash-es` in a greenfield `next.js 10.x` project?

**Comment by palerdot** [comment]
> mmh weird, [as you can see here](https://github.com/martpie/next-transpile-modules/blob/master/src/__tests__/__files__/pages/test-npm-module.jsx), `lodash-es` works well and test passes, maybe it's a `isNumber` thing 🤔

Is there a way the test can find out things are passing in individual next.js versions? The problem I think lies in `next.js 10.x` and corresponding compatibility stuffs wrt to this library.

**Comment by palerdot** [comment]
Update: https://codesandbox.io/s/agitated-moore-6r1hx?file=/pages/index.js works fine suddenly. It was not working when I created the sandbox. I no longer understand where the problem lies. Any pointers is appreciated.

**Comment by martpie** [comment]
You have to restart `next` if you do modify the config, otherwise it's not applied.

**Comment by palerdot** [comment]
Hmm ... In code sandbox, I just refreshed the whole page after making `next.config.js` and was not working for like multiple times in a row.

**Comment by martpie** [comment]
Well, I guess case closed then 👍

**Comment by palerdot** [comment]
> Well, I guess case closed then 👍 I can't really tell you what went wrong

can you keep this open till there is some idea on what is going on here? Closing this just leave people like me in lurch ...

**Comment by palerdot** [comment]
The original sandbox I shared is still not working - https://codesandbox.io/s/serene-worker-h094e?file=/pages/index.js.

**Comment by palerdot** [comment]
Just to be clear, the intermediate sandbox I created to check with vanilla `lodash-es` / `next-transpile-modules` was what started working. The original issue still stands, and things are not working consistently both in codesandbox and in local.

**Comment by palerdot** [comment]
I was able to make this work by adding my library to the list of packages that needs to be transpiled, even though my module exports common js ... 

sample `next.config.js` that worked for me 
```javascript
const withTM = require("next-transpile-modules")([
  "lodash-es",
  "react-d3-speedometer"
]);

module.exports = withTM();
```

**Comment by martpie** [comment]
I have a theory.

Can you tell me where "lodash-es" is located? In your `node_modules`? or is it installed in your `react-d3-speedometer` `node_modules`?

If the latter one, was it because you installed the package locally (`yarn link ...`) or did you install `react-d3-speedometer` from `npm`?

**Comment by martpie** [comment]
What I see could have happened is you have 2 version of `lodash-es` installed in your `node_modules`, one at the root of `node_modules`, and one in `node_modules/react-d3-speedometer/node_modules`

**Comment by palerdot** [comment]
> Can you tell me where "lodash-es" is located? In your node_modules? 
It is inside the app's `node_modules`. The package is installed from `npm`. Not linked locally from `yarn link`.

Following is the exported 'commonjs' file from my library where the error occurs.
```javascript
"use strict";var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:!0}),exports.sumArrayTill=sumArrayTill,exports.calculateSegmentStops=calculateSegmentStops,exports.calculateNeedleHeight=calculateNeedleHeight,exports.calculateSegmentLabelCount=calculateSegmentLabelCount,exports.calculateScale=calculateScale,exports.calculateTicks=calculateTicks,exports.formatCurrentValueText=formatCurrentValueText,exports.deg2rad=deg2rad,exports.centerTranslation=centerTranslation,exports.getRadius=getRadius;var _isNumber2=_interopRequireDefault(require("lodash-es/isNumber")),_sum2=_interopRequireDefault(require("lodash-es/sum")),_isEmpty=_interopRequireDefault(require("lodash-es/isEmpty")),_isArray=_interopRequireDefault(require("lodash-es/isArray")),_head2=_interopRequireDefault(require("lodash-es/head")),_last2=_interopRequireDefault(require("lodash-es/last")),_drop2=_interopRequireDefault(require("lodash-es/drop")),_times2=_interopRequireDefault(require("lodash-es/times")),_take2=_interopRequireDefault(require("lodash-es/take")),_d=require("d3");function sumArrayTill(a,b){return(0,_sum2["default"])((0,_take2["default"])(a,b))}function calculateSegmentStops(a){var b=a.tickData,c=a.customSegmentStops,d=a.min,e=a.max;if(!(0,_isArray["default"])(c)||(0,_isEmpty["default"])(c))return b;if((0,_head2["default"])(c)!==d)throw new Error("First value should be equivalent to min value given. Current min value - ".concat(d));if((0,_last2["default"])(c)!==e)throw new Error("Last value should be equivalent to max value given. Current min value - ".concat(e));var f=c.map(function(a,b){return 0===b?void 0:(a-c[b-1])/(e-d)});return(0,_drop2["default"])(f)}function calculateNeedleHeight(a){var b=a.heightRatio,c=a.radius;if(0>b||1<b)throw new Error("Invalid needleHeightRatio given - ".concat(b));return Math.round(c*b)}function calculateSegmentLabelCount(a){var b=a.maxSegmentLabelCount,c=a.segmentCount,d=parseInt(b,10),e=parseInt(c,10);return(0,_isNumber2["default"])(d)&&0<=d&&d<=e?d:e}function calculateScale(a){var b=a.min,c=a.max,d=a.segments;return(0,_d.scaleLinear)().range([0,1]).domain([b,c])}function calculateTicks(a,b){var c=b.min,d=b.max,e=b.segments,f=[];f=a.ticks(e);var g=((0,_last2["default"])(f)!==d||e<f.length)&&1<f.length;if(g){f=[c],(0,_times2["default"])(e,function(a){f.push(c+(a+1)*((d-c)/e))})}return 1===f.length&&(f=[c,d]),f}function formatCurrentValueText(a,b){var c=b.labelFormat(a),d=b.currentValuePlaceholderStyle;return b.currentValueText.replace(d,c)}function deg2rad(a){return a*Math.PI/180}function centerTranslation(a,b,c){return"translate(".concat(a+b,", ").concat(a+c,")")}function getRadius(a){return a.width/2}
```

**Comment by martpie** [comment]
But when you open your `node_modules` folder, is there anything in `node_modules/react-d3-speedometer/node_modules`?

**Comment by palerdot** [comment]
Nope ... no `node_modules` inside `react-d3-speedometer` ... just `dist` folder

**Comment by martpie** [comment]
Ok, really weird 🤔
