### ISSUE TITLE
[nextjs 8] Packages are undefined

### ISSUE THREAD

**Issue by ReggaePanda** [martpie/next-transpile-modules#18]
With nextJS 7 it works fine, but with next's 8 my imports are undefined.
<details>
 <summary>next's.config.js</summary>

```js
// @ts-check
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules');
const withTypescript = require('@zeit/next-typescript');
const withLess = require('@zeit/next-less');
const path = require('path');

const nextConfig = {
  webpack: (config, options) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      '../../theme.config$': path.resolve('./assets/styles/theme.config'),
      'styled-components': require.resolve('styled-components'),
    };

    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            publicPath: './',
            outputPath: 'static/',
            name: '[name].[ext]',
          },
        },
      },
    ];

    return config;
  },
};

module.exports = withPlugins(
  [
    [withLess],
    [
      withTM,
      {
        transpileModules: [
          '@myproject/common',
          '@myproject/controller',
          '@myproject/ui',
        ],
      },
    ],
    [withTypescript],
  ],
  nextConfig,
);
```

</details>

<details>
 <summary>package.json</summary>

```json
{
    "name": "@myproject/web",
    "version": "1.0.0",
    "license": "ISC",
    "scripts": {
        "dev": "nodemon server/index.ts",
        "build": "next build && tsc --project tsconfig.server.json",
        "start": "NODE_ENV=production node .next/production-server/index.js",
        "lint": "tslint --project tsconfig.json && yarn typecheck",
        "typecheck": "tsc --noEmit",
        "pre-commit": "yarn lint && yarn typecheck",
        "generate": "gql-gen",
        "cy": "cypress open",
        "cy:run": "cypress run"
    },
    "dependencies": {
        "@myproject/common": "1.0.0",
        "@myproject/controller": "1.0.0",
        "@myproject/ui": "1.0.0",
        "@types/cookie": "0.3.2",
        "@zeit/next-typescript": "1.1.1",
        "apollo-cache-inmemory": "1.4.2",
        "apollo-client": "2.4.12",
        "apollo-link-context": "1.0.14",
        "apollo-link-http": "1.5.11",
        "cookie": "0.3.1",
        "formik": "1.5.0",
        "graphql-tag": "2.10.1",
        "isomorphic-unfetch": "3.0.0",
        "lodash.get": "4.4.2",
        "next": "8.0.1",
        "next-compose-plugins": "2.1.1",
        "prop-types": "15.7.1",
        "react": "16.8.1",
        "react-apollo": "2.4.1",
        "react-dom": "16.8.1",
        "semantic-ui-less": "2.4.1",
        "semantic-ui-react": "0.85.0",
        "styled-components": "4.1.3",
        "typescript-babel-jest": "1.0.6"
    },
    "devDependencies": {
        "@babel/core": "7.2.2",
        "@types/lodash.get": "4.4.4",
        "@types/next": "8.0.0",
        "@types/react": "16.8.2",
        "@types/styled-components": "4.1.8",
        "@zeit/next-less": "1.0.1",
        "babel-plugin-styled-components": "1.10.0",
        "cypress": "^3.1.5",
        "file-loader": "3.0.1",
        "graphql-code-generator": "0.16.1",
        "graphql-codegen-typescript-client": "0.16.1",
        "graphql-codegen-typescript-common": "0.16.1",
        "graphql-codegen-typescript-react-apollo": "0.16.1",
        "less": "3.9.0",
        "next-transpile-modules": "2.0.0",
        "nodemon": "1.18.10",
        "prettier": "1.16.4",
        "ts-node": "8.0.2",
        "typescript": "3.3.3",
        "url-loader": "1.1.2"
    },
    "bundledDependencies": [
        "@myproject/server"
    ]
}
```
</details>

---

example project branch: https://github.com/ReggaePanda/React-Native-Web-TypeScript-Prettier-Boilerplate/tree/core/nex-8.x

**Comment by martpie** [comment]
This is my log when running your project: 

```
@myproject/web: [nodemon] 1.18.10
@myproject/web: [nodemon] to restart at any time, enter `rs`
@myproject/web: [nodemon] watching: server/**/*.ts
@myproject/web: [nodemon] starting `ts-node server/index.ts`
@myproject/web: > Using "webpackDevMiddleware" config function defined in default.
@myproject/web: [4:53:13 PM] Compiling server
@myproject/web: [4:53:16 PM] Compiled server in 3s
@myproject/web: [4:53:17 PM] Compiling client
@myproject/web: > Using external babel configuration
@myproject/web: > Location: "/Users/pierre/dev/temp/packages/web/.babelrc"
@myproject/web: [4:53:19 PM] Compiled client in 2s
@myproject/web:  DONE  Compiled successfully in 6232ms4:53:19 PM
@myproject/web: > Ready on http://localhost:3000
@myproject/web:  WAIT  Compiling...4:53:19 PM
@myproject/web: [4:53:20 PM] Compiling client
@myproject/web: [4:53:20 PM] Compiled client in 105ms
@myproject/web:  DONE  Compiled successfully in 142ms4:53:20 PM
```

I have some errors related to ENV variables not present, but I guess it's unrelated.

`yarn build` works fine too. I am not sure where the problem is.

**Comment by martpie** [comment]
Here's my log when running `yarn dev`:

```
➜  temp git:(78f6ae0) yarn run dev
yarn run v1.13.0
$ yarn build:common && yarn build:controller && yarn build:ui && lerna run dev --parallel
$ yarn --cwd packages/common build
$ rimraf dist
$ tsc
$ yarn --cwd packages/controller build
$ rimraf dist
$ tsc
$ yarn --cwd packages/ui build
$ rimraf dist && tsc
lerna notice cli v3.11.1
lerna info Executing command in 6 packages: "yarn run dev"
@myproject/app: $ yarn start
@myproject/server: $ ts-node-dev --respawn ./src/index.ts
@myproject/common: $ tsc --watch
@myproject/controller: $ tsc --watch
@myproject/ui: $ start-storybook -p 9001 -c .storybook
@myproject/web: $ nodemon server/index.ts
@myproject/controller:
5:13:16 PM - Starting compilation in watch mode...
@myproject/common:
5:13:16 PM - Starting compilation in watch mode...
@myproject/app: $ node node_modules/react-native/local-cli/cli.js start
@myproject/web: [nodemon] 1.18.10
@myproject/web: [nodemon] to restart at any time, enter `rs`
@myproject/web: [nodemon] watching: server/**/*.ts
@myproject/web: [nodemon] starting `ts-node server/index.ts`
@myproject/server: Using ts-node version 8.0.2, typescript version 3.3.3
@myproject/ui: info @storybook/react v4.1.11
@myproject/ui: info
@myproject/ui: info => Loading presets
@myproject/ui: info => Loading presets
@myproject/ui: info => Loading custom addons config.
@myproject/ui: info => Using base config because react-scripts is not installed.
@myproject/ui: info => Loading custom webpack config (full-control mode).
@myproject/ui: info => Using base config because react-scripts is not installed.
@myproject/app: ┌──────────────────────────────────────────────────────────────────────────────┐
@myproject/app: │                                                                              │
@myproject/app: │  Running Metro Bundler on port 8081.                                         │
@myproject/app: │                                                                              │
@myproject/app: │  Keep Metro running while developing on any JS projects. Feel free to        │
@myproject/app: │  close this tab and run your own Metro instance if you prefer.               │
@myproject/app: │                                                                              │
@myproject/app: │  https://github.com/facebook/react-native                                    │
@myproject/app: │                                                                              │
@myproject/app: └──────────────────────────────────────────────────────────────────────────────┘
@myproject/common: 5:13:23 PM - Found 0 errors. Watching for file changes.
@myproject/app: Looking for JS files in
@myproject/app:    /Users/pierre/dev/temp/packages/app
@myproject/app:    /Users/pierre/dev/temp
@myproject/controller: 5:13:25 PM - Found 0 errors. Watching for file changes.
@myproject/web: > Using "webpackDevMiddleware" config function defined in default.
@myproject/web: ℹ Compiling Server                                         webpackbar 17:13:28
@myproject/server: Error: Cannot parse config file: '/Users/pierre/dev/temp/packages/server/config/default.ts': MissingEnvVarsError: The following variables were defined in .env.example but are not present in the environment:
@myproject/server:   GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, FACEBOOK_APP_ID, FACEBOOK_APP_SECRET, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, SESSION_SECRET
@myproject/server: Make sure to add them to .env or directly to the environment.
@myproject/server: If you expect any of these variables to be empty, you can use the allowEmptyValues option:
@myproject/server: require('dotenv-safe').config({
@myproject/server:   allowEmptyValues: true
@myproject/server: });
@myproject/server: Also, the following error was thrown when trying to read variables from  .env:
@myproject/server: ENOENT: no such file or directory, open '/Users/pierre/dev/temp/packages/server/.env'
@myproject/server:     at Config.util.parseFile (/Users/pierre/dev/temp/node_modules/config/lib/config.js:838:11)
@myproject/server:     at /Users/pierre/dev/temp/node_modules/config/lib/config.js:600:28
@myproject/server:     at Array.forEach (<anonymous>)
@myproject/server:     at /Users/pierre/dev/temp/node_modules/config/lib/config.js:596:14
@myproject/server:     at Array.forEach (<anonymous>)
@myproject/server:     at Config.util.loadFileConfigs (/Users/pierre/dev/temp/node_modules/config/lib/config.js:595:13)
@myproject/server:     at new Config (/Users/pierre/dev/temp/node_modules/config/lib/config.js:136:27)
@myproject/server:     at Object.<anonymous> (/Users/pierre/dev/temp/node_modules/config/lib/config.js:1643:31)
@myproject/server:     at Module._compile (internal/modules/cjs/loader.js:689:30)
@myproject/server:     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
@myproject/server: [ERROR] 17:13:31 Error: Cannot parse config file: '/Users/pierre/dev/temp/packages/server/config/default.ts': MissingEnvVarsError: The following variables were defined in .env.example but are not present in the environment:
@myproject/server:   GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, FACEBOOK_APP_ID, FACEBOOK_APP_SECRET, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, SESSION_SECRET
@myproject/server: Make sure to add them to .env or directly to the environment.
@myproject/server: If you expect any of these variables to be empty, you can use the allowEmptyValues option:
@myproject/server: require('dotenv-safe').config({
@myproject/server:   allowEmptyValues: true
@myproject/server: });
@myproject/server: Also, the following error was thrown when trying to read variables from  .env:
@myproject/server: ENOENT: no such file or directory, open '/Users/pierre/dev/temp/packages/server/.env'
@myproject/ui: ℹ ｢atl｣: Using typescript@3.1.3 from typescript
@myproject/ui: ℹ ｢atl｣: Using tsconfig.json from /Users/pierre/dev/temp/packages/ui/tsconfig.json
@myproject/web: ℹ Compiling Client                                         webpackbar 17:13:32
@myproject/web: > Using external babel configuration
@myproject/web: > Location: "/Users/pierre/dev/temp/packages/web/.babelrc"
@myproject/web: ✔ Server: Compiled successfully in 6.48s                   webpackbar 17:13:34
@myproject/web: ✔ Client: Compiled successfully in 3.05s                   webpackbar 17:13:35
@myproject/web:  DONE  Compiled successfully in 7238ms5:13:35 PM
@myproject/web: > Ready on http://localhost:3000
@myproject/web:  WAIT  Compiling...5:13:35 PM
@myproject/web: ℹ Compiling Client                                         webpackbar 17:13:36
@myproject/web: ✔ Client: Compiled successfully in 236.39ms                webpackbar 17:13:36
@myproject/web:  DONE  Compiled successfully in 274ms5:13:36 PM
@myproject/app: Loading dependency graph, done.
@myproject/ui: ℹ ｢atl｣: Checking started in a separate process...
@myproject/ui: ℹ ｢atl｣: Time: 226ms
@myproject/ui: webpack built fc8457db5b1b5b838e30 in 43355ms
@myproject/ui: ╭──────────────────────────────────────────────────╮
@myproject/ui: │                                                  │
@myproject/ui: │   Storybook 4.1.11 started                       │
@myproject/ui: │   45 s for manager and 45 s for preview          │
@myproject/ui: │                                                  │
@myproject/ui: │   Local:            http://localhost:9001/       │
@myproject/ui: │   On your network:  http://172.16.1.219:9001/    │
@myproject/ui: │                                                  │
@myproject/ui: ╰──────────────────────────────────────────────────╯
@myproject/controller:
5:14:06 PM - File change detected. Starting incremental compilation...
@myproject/controller: 5:14:07 PM - Found 0 errors. Watching for file changes.
```

I do not see anything wrong here. `yarn build` runs without any problem (on the branch `core/nex-8.x`)

**Comment by ReggaePanda** [comment]
sorry, my readme isn't complete.

but to see my issue you can do the following
first pull branch (I changed something)

```bash
yarn install
yarn build
cd packages/web
yarn dev
```

then u can see in your console a console.log > `DEBUG next-transpile-modules { meQuery: undefined }`
https://github.com/ReggaePanda/React-Native-Web-TypeScript-Prettier-Boilerplate/blob/9404a157c553b7e11bbc7d2ae439bbc776407157/packages/web/pages/index.tsx#L18

the full repo works when u add an `packages/server/.env` file (see `.env.example` values can be random) and start a postgrSql and Redis server. later I add docker to make it more easy 😄

**Comment by martpie** [comment]
I am pretty sure the error is coming from your setup and not this plugin. Your imports are transformed into `require()` by TypeScript, and the packages seem to not be installed (cf screenshot), so the require returns `undefined`.

Did you also have a look at the FAQ? https://github.com/martpie/next-transpile-modules#i-have-trouble-making-it-work-with-lerna

<img width="363" alt="screen shot 2019-02-13 at 20 08 37" src="https://user-images.githubusercontent.com/1311607/52736854-2e1c8b80-2fcb-11e9-9519-26ef003f5b6c.png">

**Comment by ReggaePanda** [comment]
@martpie thank you :smiley

I try to fix it with adding it to `nohoist` in package.json file. It was listed in the `packages/web/node_modules` directory , but this doesn't work.

finally I added `aliases` in the `next.config.js` and it works 🎉
Maybe worth an entry in the FAQ

```js
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules');
const withTypescript = require('@zeit/next-typescript');
const withLess = require('@zeit/next-less');
const path = require('path');

const nextConfig = {
  webpack: (config, options) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      '../../theme.config$': path.resolve('./assets/styles/theme.config'),
      'styled-components': require.resolve('styled-components'),
      '@myproject/common': require.resolve('@myproject/common'),
      '@myproject/controller': require.resolve('@myproject/controller'),
      '@myproject/ui': require.resolve('@myproject/ui'),
    };
    return config;
  },
};

module.exports = withPlugins(
  [
    [withLess],
    [
      withTM,
      {
        transpileModules: [
          '@myproject/common',
          '@myproject/controller',
          '@myproject/ui',
        ],
      },
    ],
    [withTypescript],
  ],
  nextConfig,
);
```

**Comment by martpie** [comment]
Mmmh, this is interesting. I don't understand how does Lerna/npm resolves those packages though:

```
'@myproject/common': require.resolve('@myproject/common'),
'@myproject/controller': require.resolve('@myproject/controller'),
'@myproject/ui': require.resolve('@myproject/ui'),
```

Where are those files physically? I do not see them in `node_modules`, and I do not see any lock files that could indicate Node where to actually look for those files.

**Comment by martpie** [comment]
Oh, I think I get it. Does Lerna install those packages "globally" in a place like the HOME fodler? And then `require.resolve` will by default look in this same directory unless the first parameter is a relative path?

https://nodejs.org/api/modules.html#modules_require_resolve_request_options

**Comment by ReggaePanda** [comment]
physically the files are in the root `node_modules`.
the lock file is also in the root dir.

I am not sure how it works. 😇 but I think you are right.

**Comment by martpie** [comment]
Looks quite similar: 

https://github.com/lerna/lerna/issues/1049#issuecomment-335014011

This plugin actually works because our `includes`/`exludes` rules matches also `node_modules` in parent directories. Not sure if a bug or a feature though.

Let's leave things that way for now.

I'll add a section in the FAQ about this problem.
