### ISSUE TITLE
Issue with babel when transpiling external component with react-spring

### ISSUE THREAD

**Issue by fillipvt** [martpie/next-transpile-modules#19]
Hello,

I'm not sure if this goes here but if doesn't let me know. I'm using a monorepo with `yarn workspaces` and `lerna`. The package `main` (next.js app `8.0.2-canary.3`) use the following dependecies.

I also have a [reproduction repo here](https://github.com/fillipvt/repro-error-1).

```
  "dependencies": {
    "shared": "1.0.0",
    "@emotion/core": "^10.0.7",
    "@emotion/styled": "^10.0.7",
    "babel-plugin-emotion": "^10.0.6",
    "next": "8.0.2-canary.3",
    "next-transpile-modules": "^2.0.0",
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-spring": "^8.0.7"
  }
```

This is the current error log:

```
Compiled successfully!

  > Ready on http://localhost:3000

Note that pages will be compiled when you first load them.
/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/node_modules/react-spring/renderprops.js:1
(function (exports, require, module, __filename, __dirname) { import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.react-spring/renderprops (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:338:18)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/Text.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:162:82)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
    at Module.../../node_modules/shared/Text/index.js (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:222:63)
    at __webpack_require__ (/Users/Felipe/Local_Projects/Aprender/bugs/objectWithoutPropertiesLoose/packages/main/.next/server/static/development/pages/index.js:23:31)
```

It mentions errors in babel and react-spring.

Is there something I'm not implementing correctly? 

Any comment is appreciated.

Thank you

**Comment by martpie** [comment]
I think you should have a look at the FAQ in the README ;)

```
> lerna bootstrap

lerna notice cli v3.13.0
lerna ERR! EWORKSPACES Yarn workspaces are configured in package.json, but not enabled in lerna.json!
lerna ERR! EWORKSPACES Please choose one: useWorkspaces = true in lerna.json, or remove package.json workspaces config
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! repro-error-1@1.0.0 lerna:bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the repro-error-1@1.0.0 lerna:bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pierre\AppData\Roaming\npm-cache\_logs\2019-02-20T23_34_09_489Z-debug.log
```

here's what happen anyway when I try to `lerna:bootstrap`. I think you setup something wrong :)

**Comment by fillipvt** [comment]
Thanks for answering @martpie 

I removed `lerna`. I copy pasted from the original repo where I had the problem, but to showcase what's going on in here there's no need for `lerna`.

I've updated the repo and in the `README.md` described some quick steps to reproduce the error. If you could once again take a look I would highly appreciate it. Thank you.

**Comment by fillipvt** [comment]
Quick note, when using `react-spring 7.2.10` everything works. I've also taken steps to report there but not sure if this also has anything to do with the transpilation with `next-transpile-modules`.

**Comment by martpie** [comment]
Looking at the `react-spring` files, they do not seem transpiled to require/module.exports. Adding `react-spring` to the list of `transpileModules` seems to fix the issue, but it looks like an issue with the library itself.

**Comment by martpie** [comment]
Found it. I think you'll need to import the `.cjs` files instead of the normal ones.

![capture](https://user-images.githubusercontent.com/1311607/53136108-0191e200-357e-11e9-9eed-d4dbed328635.PNG)

**Comment by martpie** [comment]
More about this: https://github.com/react-spring/react-spring/issues/494

**Comment by fillipvt** [comment]
@martpie thank you! Since this is unrelated to `next-transpile-modules` I'll be closing this issue.

Thanks for pointing me in the right direction. I was totally confused as to why `react-spring` suddenly stopped working.
