### ISSUE TITLE
Modules not transpiled 

### ISSUE THREAD

**Issue by TxHawks** [martpie/next-transpile-modules#20]
I am trying to transpile local packages in a monorepo that is managed by Lerna and Yarn workspaces.

The packages use Flow, so it's very easy to see that the code does not get transpiled, because it causes syntax errors. However, it seems that its not only the Flow preset that isn't being applied. Even if I point to a code where Flow annotations have been striped, but that was not transpiled down to es5, the code does not get transformed at all.

I'm pretty sure it is me who is doing something wrong, but cannot figure out what. I have Babel config files in both the Next app and consumed package, and have followed [the instructions in the README](https://github.com/martpie/next-transpile-modules#but-i-really-need-to-make-it-work-with-lerna) on aliasing packages when using Lerna.

[Here's a repository that makes a minimal reproduction](https://github.com/TxHawks/next-flow-transpile-repro)

**Comment by martpie** [comment]
This is the log I get when running `yarn && yarn bootstrap`


```
$ npm run build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/pierre/Desktop/test-ntm/next-flow-transpile-repro/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '$ npm run build\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   'npm ERR! missing script: build\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/pierre/.npm/_logs/2019-02-22T09_17_50_668Z-debug.log\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by TxHawks** [comment]
Yes, oops, sorry. I removed the build by mistake when creating the reproduction repository.

There are things there that are over complicated because before without transpiling packages, all internal packages had to be built before they could be used, so there is a `prepare` script there.

I think I have found the initial issue I had, and that was that I thought having `transpileModules: [ '@haaretz' ]` will select all `@haaretz` packages, while it turns out I have to specify they one by one (which makes sense really, though it would be nice to be able to have do this with a regex).

One of the first things I did was to try and change `transpileModules` to `[ '@haaretz/htz-components' ]`, but then saw #19, and realized it actually need be `['@haaretz/test-next-app', '@haaretz/htz-components']`, to also include the Next package. This was a bit counter intuitive, but okay.

This solved the problem in the reproduction repo, and some of the problem in the original repository.

I now get the following error when trying to build in the original repository:
```
ModuleBuildError: Module build failed (from node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: Cannot read property 'name' of undefined
    at node_modules/styled-jsx/dist/_utils.js:135:22
    at Array.some (<anonymous>)
    at isStyledJsx (node_modules/styled-jsx/dist/_utils.js:134:104)
    at findStyles (node_modules/styled-jsx/dist/_utils.js:142:7)
    at PluginPass.enter (node_modules/styled-jsx/dist/babel.js:80:44)
    at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
    at runLoaders (node_modules/webpack/lib/NormalModule.js:301:20)
    at node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.err (node_modules/next/node_modules/babel-loader/lib/index.js:45:103)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (node_modules/next/dist/build/index.js:69:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

No idea what could be the cause of this...

**Comment by TxHawks** [comment]
This is the offending bit in styled-jsx:
```js
var isStyledJsx = function isStyledJsx(_ref2) {
  var el = _ref2.node;
  return t.isJSXElement(el) && el.openingElement.name.name === 'style' && el.openingElement.attributes.some(function (attr) {
    return attr.name.name === _constants.STYLE_ATTRIBUTE;  // <-- THIS LINE
  });
};
```

and if I change it to 
```js
    return attr.name && attr.name.name === _constants.STYLE_ATTRIBUTE;
```

Everything works fine. I don't really understand what could possibly be going on here, as, like I said, we don't even use style-jsx anywhere, and it doesn't happen when not using `next-transpile-modules`

**Comment by martpie** [comment]
Sorry for the delay, I am in holidays and I was working on other open-source stuff. I will look at it this week-end :)

**Comment by TxHawks** [comment]
It's all good. I'm patching styled-jsx with a postinstall script for the time being, so urgency is really down to a minimum. Also opened an issue in the style-jsx repo, but no response there as of yet

**Comment by martpie** [comment]
Did you manage to make it all work @TxHawks ?

**Comment by TxHawks** [comment]
Not really, but worked around it with a `postinstall` hook. Guess we can close
