### ISSUE TITLE
Not working with @react-three/xr

### ISSUE THREAD

**Issue by FRMR1** [martpie/next-transpile-modules#229]
- [x ] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x ] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?

NPM package: @react-three/xr

**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).

I'm trying to use next-transpile-modules on @react-three/xr and it is throwing the following error: 

```./node_modules/@react-three/xr/dist/index.cjs.js:13:17
Module not found: ESM packages (three/examples/jsm/loaders/GLTFLoader) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals```

Import trace for requested module:
./pages/index.js

https://nextjs.org/docs/messages/module-not-found
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):

https://codesandbox.io/s/musing-jones-1w4zt

**Expected behavior**

For @react-three/xr to be transpiled and loaded. 

**Setup**

- Next.js version: 10.2.3
- `next-transpile-modules` version: 7.3.0
- Node.js version: 10.20.1
- `npm`/`yarn` version: 
- Operating System:
- Webpack 4 or 5: 4

**Additional context**

**Comment by martpie** [comment]
Can you paste the whole debug log? (cf. readme)

**Comment by FRMR1** [comment]
Sorry where would I find this?

**Comment by FRMR1** [comment]
I tried this from the FAQ:
```
How do I find out which package is causing a runtime exception?

    add config.optimization.minimize = false; to you next.config.js's Webpack configuration
    run a production build
    run it on the browser throwing the error
    open the console, jump to the line where it failed
    goes a little bit up in the lines of code, and check the Webpack comments telling you which module is affected
```

But I get a build error on the production build:
```
> Build error occurred
/Users/macbookpro/Sites/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.T18M (/Users/macbookpro/Sites/web app/frontend/.next/server/pages/store.js:16087:18)
    at __webpack_require__ (/Users/macbookpro/Sites/web app/frontend/.next/server/pages/store.js:23:31)
    at Object.6yQC (/Users/macbookpro/Sites/web app/frontend/.next/server/pages/store.js:7591:25) {
  type: 'SyntaxError'
}
```

**Comment by martpie** [comment]
> Sorry where would I find this?

Enable the debug flag https://github.com/martpie/next-transpile-modules#withtmtranspilemodules--options

and just share the content of your terminal here, from the moment you run the command to the error

**Comment by FRMR1** [comment]
This is the terminal log from the moment I navigate to the URL which loads `@react-three/xr`:
```
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - build page: /next/dist/pages/_error
event - compiled successfully
event - build page: /store
wait  - compiling...
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/OculusHandModel.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/DRACOLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/XRControllerModelFactory.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/OculusHandModel.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/TextureLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/DRACOLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/XRControllerModelFactory.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/TextureLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/XRHandMeshModel.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/webxr/XRHandMeshModel.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/libs/motion-controllers.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/constants.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/ImageLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Loader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/textures/Texture.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/libs/motion-controllers.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/constants.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/ImageLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Loader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/textures/Texture.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/GLTFLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/constants.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Loader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Loader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/constants.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/LoadingManager.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Cache.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/extras/ImageUtils.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/core/EventDispatcher.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/Vector2.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/MathUtils.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/Matrix3.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/LoadingManager.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/loaders/Cache.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/core/EventDispatcher.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/MathUtils.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/Vector2.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/math/Matrix3.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/src/extras/ImageUtils.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/xr/dist/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/SVGLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/examples/jsm/loaders/SVGLoader.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.cjs.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@react-three/drei/index.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.js
next-transpile-modules - transpiled: /Users/macbookpro/Sites/phasm/web app/frontend/node_modules/three/build/three.module.js
event - compiled successfully
/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@webxr-input-profiles/motion-controllers:1:18)
    at Object.@webxr-input-profiles/motion-controllers (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:1093:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./node_modules/@react-three/xr/dist/index.cjs.js:25:25)
    at Object../node_modules/@react-three/xr/dist/index.cjs.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:764:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./components/VR/Stores/GNOS/UI/ProductModel/index.js:11:73)
    at Module../components/VR/Stores/GNOS/UI/ProductModel/index.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:536:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@webxr-input-profiles/motion-controllers:1:18)
    at Object.@webxr-input-profiles/motion-controllers (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:1093:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./node_modules/@react-three/xr/dist/index.cjs.js:25:25)
    at Object../node_modules/@react-three/xr/dist/index.cjs.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:764:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./components/VR/Stores/GNOS/UI/ProductModel/index.js:11:73)
    at Module../components/VR/Stores/GNOS/UI/ProductModel/index.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:536:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@webxr-input-profiles/motion-controllers:1:18)
    at Object.@webxr-input-profiles/motion-controllers (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:1093:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./node_modules/@react-three/xr/dist/index.cjs.js:25:25)
    at Object../node_modules/@react-three/xr/dist/index.cjs.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:764:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./components/VR/Stores/GNOS/UI/ProductModel/index.js:11:73)
    at Module../components/VR/Stores/GNOS/UI/ProductModel/index.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:536:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@webxr-input-profiles/motion-controllers:1:18)
    at Object.@webxr-input-profiles/motion-controllers (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:1093:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./node_modules/@react-three/xr/dist/index.cjs.js:25:25)
    at Object../node_modules/@react-three/xr/dist/index.cjs.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:764:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./components/VR/Stores/GNOS/UI/ProductModel/index.js:11:73)
    at Module../components/VR/Stores/GNOS/UI/ProductModel/index.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:536:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@webxr-input-profiles/motion-controllers:1:18)
    at Object.@webxr-input-profiles/motion-controllers (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:1093:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./node_modules/@react-three/xr/dist/index.cjs.js:25:25)
    at Object../node_modules/@react-three/xr/dist/index.cjs.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:764:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
    at eval (webpack-internal:///./components/VR/Stores/GNOS/UI/ProductModel/index.js:11:73)
    at Module../components/VR/Stores/GNOS/UI/ProductModel/index.js (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:536:1)
    at __webpack_require__ (/Users/macbookpro/Sites/phasm/web app/frontend/.next/server/pages/store.js:23:31)
```

**Comment by martpie** [comment]
```/Users/macbookpro/Sites/phasm/web app/frontend/node_modules/@webxr-input-profiles/motion-controllers/dist/motion-controllers.module.js:397
export { Constants, MotionController, fetchProfile, fetchProfilesList };
^^^^^^

SyntaxError: Unexpected token 'export'
```

well to me it's pretty clear which package is responsible, it's there in the log -> @webxr-input-profiles

**Comment by FRMR1** [comment]
So how would I transpile this package so I can use @react-three/xr with nextjs?

**Comment by martpie** [comment]
well you just add it to the list of transpiled packages : 

```const withTM = require('next-transpile-modules')([..., '@webxr-input-profiles']);```

**Comment by FRMR1** [comment]
Of course. Thank you.
