### ISSUE TITLE
Broken with experimental app directory!

### ISSUE THREAD

**Issue by rafegoldberg** [martpie/next-transpile-modules#287]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

### Are you trying to transpile a local package or an npm package?
Local package.

### Describe the bug
This little plugin is fantastic; I even got it set up to transpile my UI modules from a sibling subpackage in a monorepo [per the docs](https://github.com/martpie/next-transpile-modules/#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react):

```js
module.exports = {
  webpack: (config, options) => {
    if (options.isServer) config.externals = ['react', ...config.externals];
    config.resolve.alias['react'] = path.resolve(__dirname, '.', 'node_modules', 'react');
  },
}
```

But when I try to [turn on the new experimental app directory](https://beta.nextjs.org/docs/api-reference/next.config.js#appdir), the build fails and throws the following error:

```
Error: Currently React only supports one RSC renderer at a time.
    at createRequest (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1096:35)
    at Module.renderToReadableStream (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:2056:39)
    at createRSCStream (~/repo/packages/next-dash/node_modules/next/dist/server/app-render.js:292:38)
    at ServerComponentWrapper (~/repo/packages/next-dash/node_modules/next/dist/server/app-render.js:304:27)
    at renderWithHooks (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7681:16)
    at renderIndeterminateComponent (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7755:15)
    at renderElement (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7990:7)
    at renderNodeDestructiveImpl (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8157:11)
    at renderNodeDestructive (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8129:14)
    at renderContextProvider (~/repo/packages/next-dash/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7954:3)
```
 
### To Reproduce
- Scaffold out a monorepo with a `ui/` components folder and a `next/` application.
- [Configure the `next/` app to transpile `ui/` components using this plugin](https://github.com/martpie/next-transpile-modules/#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react).
- Start the dev server; note the app compiles as expected!
- Now enable the experimental app dir and set up the most basic `next/app/page.jsx` example
- Try rerunning the server and loading the root route; note the error in your logs. 😬

### Expected behavior
I expected the app to transpile local components, and build correctly.

### Setup

- **Plugin**: `v10.0.0`
- **Next**: `v13.0.5`
- **Node**: `v16.8.0`
- **NPM**: `v7.21.0`
- **OS**: macOS `v12.3.1`
- **Webpack**: `v5.65.0`

**Comment by martpie** [comment]
Yeah I think it's because of the same issue as #283 

Out of curiosity, could you disable `next-transpile-modules`, use:

```
module.exports = {
  experimental: {
    transpilePackages: ['FILL STUFF HERE'],
  },
};
```

And tell me if it solves it for you?

**Comment by rafegoldberg** [comment]
Hmmm, reading through the Next beta docs a bit further and just came across [this new `transpilePackages` config option](https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages). Could be related to that, potentially?

**Comment by rafegoldberg** [comment]
Yeah, so replacing this plugin with [that new transpilePackages config option](https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages) 100% fixes it! Closing this out; thanks for your time.

**Comment by martpie** [comment]
Thank you very much, happy to see the official implementation of `next-transpile-modules` covering your usecase!

**Comment by rafegoldberg** [comment]
Ahhh, appreciate the quick response @martpie! Ya beat me to it!
