### ISSUE TITLE
Broken with next 8.1.0

### ISSUE THREAD

**Issue by emirotin** [martpie/next-transpile-modules#29]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Describe the bug**

```
> Build error occurred
TypeError: Cannot read property 'map' of undefined
    at Object.webpack (/Users/emirotin/work/kirsikka-v4/node_modules/next-transpile-modules/index.js:48:43)
    at Object.webpack (/Users/emirotin/work/kirsikka-v4/node_modules/@zeit/next-css/index.js:30:27)
    at Object.webpack (/Users/emirotin/work/kirsikka-v4/node_modules/@zeit/next-source-maps/index.js:34:29)
    at Object.getBaseWebpackConfig [as default] (/Users/emirotin/work/kirsikka-v4/node_modules/next/dist/build/webpack-config.js:308:32)
    at Object.build [as default] (/Users/emirotin/work/kirsikka-v4/node_modules/next/dist/build/index.js:103:33)
    at <anonymous>
error Command failed with exit code 1.
```

**Setup**

 - Next.js version: 8.1.0
 - `next-transpile-modules` version: 2.2.0
 - Node.js version: 8
- Operating System: macOS/Linux

---

Also on a side note, there seems to be some activity in the upstream project, the master here is 8 commits behind

**Comment by martpie** [comment]
Thank you for the report, I'll investigate :)

Regarding the 8 commits behind, it does not mean anything: all these commits are merges from this repo to the upstream + README adaptation ;)

**Comment by martpie** [comment]
I can reproduce it, on it.

**Comment by Yzrsah** [comment]
I just came here to report this. Thanks!

**Comment by Yzrsah** [comment]
I just came here to report this. I thought it was going to be day of new errors, but with such expertise in the hands of martpie, I see there's nothing to worry about. Thanks!

**Comment by brandontruong** [comment]
hi @martpie , can you please provide more instructions of how to fix it?
Thanks
