### ISSUE TITLE
Root modules are not transpiled

### ISSUE THREAD

**Issue by TrySound** [martpie/next-transpile-modules#61]
**Are you trying to transpile a local package or an npm package?**

Local package

**Describe the bug**

My project structure

packages/package_name/package.json
project_name/package.json

Both package and project are included in workspaces.
Project uses package. Webpack see it linked to `../node_modules/package_name/package.json`

Here's what I see in logs

```
[ wait ]  compiling ...
req.url /en
rewritesCache was empty, new rewrites are generated at 2020-01-21T08:23:16.429Z
[ ready ] compiled successfully
[ error ] /monorepo/packages/package_name/index.js:3
export type { $FragmentRef, $FragmentRefArray } from './types.js';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Module._compile (/monorepo/node_modules/@babel/register/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.newLoader [as .js] (/monorepo/node_modules/@babel/register/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.package_name (/monorepo/project_name/.next/server/static/development/pages/webpack:/external "package_name":1:1)
    at __webpack_require__ (/monorepo/project_name/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../pages/_app.js (/monorepo/project_name/.next/server/static/development/pages/_app.js:12782:64)
    at __webpack_require__ (/monorepo/project_name/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Object.0 (/monorepo/project_name/.next/server/static/development/pages/_app.js:18112:18)
    at __webpack_require__ (/monorepo/project_name/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at /monorepo/project_name/.next/server/static/development/pages/webpack:/webpack/bootstrap:89:1
    at Object.<anonymous> (/monorepo/project_name/.next/server/static/development/pages/_app.js:94:10)
```

I edited node_modules to find a solution. In the last version I see this

```
const generateIncludes = modules => {
  return [
    new RegExp(
      `(${modules.map(safePath).join('|')})${PATH_DELIMITER}(?!.*node_modules)`,
    ),
  ];
};
```

when I remove `${PATH_DELIMITER}` all works again. So the problem is that sometimes webpack pass package path without specific module. Something like `../node_modules/package_name`.

I modified this functions to take in account both cases and everything works

```
const generateIncludes = modules => {
  return [
    new RegExp(`(${modules.map(safePath).join('|')})$`),
    new RegExp(
      `(${modules.map(safePath).join('|')})${PATH_DELIMITER}(?!.*node_modules)`,
    ),
  ];
};
```

**To Reproduce**
No reproduction yet.

**Expected behavior**
I expect to transpile my local packages.

**Setup**

- Next.js version: 9.2.0
- `next-transpile-modules` version: 3.0.0
- Node.js version: 12.10.0
- `yarn` version: 1.17.2
- Operating System: mac os mojave

**Comment by onigoetz** [comment]
Can confirm,I have the same problem and the proposed solution does the trick.

Importing a package directly, without a sub-file doesn't work in V3

**Comment by martpie** [comment]
Thanks for the report guys, I will try to reproduce it myself, but I may need your help to identify the exact issue by providing a reproduction.

What is more concerning is I probably wrote the end-to-end tests wrong, so I really need to identify what is wrong with them.

**Comment by TrySound** [comment]
Tests are not wrong, just not full.
You can set `"main": "utils/calc.js"` here
https://github.com/martpie/next-transpile-modules/blob/master/src/__tests__/__apps__/_shared/package.json#L5
and add similar page but with `import { add } from 'shared';`
https://github.com/martpie/next-transpile-modules/blob/master/src/__tests__/__apps__/basic/pages/test-local-module.jsx

**Comment by martpie** [comment]
Aaaaaah, got it! Thanks!

**Comment by martpie** [comment]
A fix will be released tonight (Western Europe time), I need to finish an integration test and we're good. Sorry guys for the delay.

**Comment by onigoetz** [comment]
No problem, I need it for work (west europe) but it can wait :) thanks for your time and work !

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Pierre de la Martinière <notifications@github.com>
Envoyé : mardi, janvier 21, 2020 6:37 PM
À : martpie/next-transpile-modules
Cc : Stéphane Goetz; Comment
Objet : Re: [martpie/next-transpile-modules] Root modules are not transpiled (#61)


A fix will be released tonight (Western Europe time), I need to finish an integration test and we're good. Sorry guys for the delay.

**Comment by martpie** [comment]
3.0.1 is out and fixing this issue :) thank you everyone!

**Comment by TrySound** [comment]
Thanks!
