### ISSUE TITLE
Monorepo external dependencies error

### ISSUE THREAD

**Issue by stephane-r** [martpie/next-transpile-modules#80]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
npm package on yarn workspaces

**Describe the bug**
Hello everybody !

I try to change simple CRA app to Next.JS app using monorepo with yarn workspaces. I my repo, i use `react-native-web` with other library like `@emotion/native` or `react-native-svg`.

I would like using your great module, but i've an error for react-native modules : 

```
SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/xx/xx/node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/xx/xx/node_modules/@emotion/native/dist/native.cjs.dev.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

This error is with `@emotion/native` but i've have the same result with `react-native-svg`.

On the current CRA app, i don't have any babel config, only custom webpack for require external module scoped.

If anyone have an idea about this problem :)

Thank you !

**Setup**

- Next.js version: latest
- `next-transpile-modules` version: latest
- Node.js version: 12
- `npm`/`yarn` version: 1.22.4
- Operating System: Ubuntu

**Comment by martpie** [comment]
This is not really related to this plugin, more to the Babel configuration. Did you try adding react native to your babel configuration?

https://stackoverflow.com/questions/57158884/syntaxerror-missing-initializer-in-const-declaration
